version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - calendar-network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: apontamentos
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario -d apontamentos"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - calendar-network

networks:
  calendar-network:
    driver: bridge

volumes:
  postgres-data:
